# Generated by Django 3.1.12 on 2025-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20250820_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='departments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
