# Generated by Django 3.1.12 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
