# Generated by Django 3.1.12 on 2025-08-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20250821_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='title_name',
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
