# Generated by Django 3.1.12 on 2025-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20250821_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=700)),
            ],
        ),
    ]
