# Generated by Django 3.1.12 on 2025-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_homepage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_page',
            name='ervices_heders',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_box',
            name='box_header',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_box',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage_box2',
            name='box_header',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_box2',
            name='sevices',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='services_page',
            name='ervices_heder',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='services_page',
            name='sevices',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
