# Generated by Django 3.1.12 on 2025-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humayan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
